(() => {
  "use strict";
  const $ = (s) => document.querySelector(s); const $$ = (s) => [...document.querySelectorAll(s)];
  const API = "/api/settlement";
  const state = { page:"dashboard", recordPage:1, recordPages:1, importRows:[], meta:{years:[],distributors:[]} };
  const titleMap = {dashboard:["OVERVIEW","대시보드"],records:["SETTLEMENTS","정산내역"],songs:["TRACKS","음원별 집계"],import:["IMPORT","정산서 가져오기"]};
  const money = (v) => `₩${Math.round(Number(v)||0).toLocaleString("ko-KR")}`;
  const num = (v) => Math.round(Number(v)||0).toLocaleString("ko-KR");
  const esc = (v) => String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
  const debounce=(fn,ms=250)=>{let t;return(...a)=>{clearTimeout(t);t=setTimeout(()=>fn(...a),ms)}};
  function showOnly(id){["#loginView","#setupView","#appView"].forEach(s=>$(s).classList.toggle("hidden",s!==id));}
  function toast(message,type="success"){const el=document.createElement("div");el.className=`toast ${type}`;el.textContent=message;$("#toastHost").append(el);setTimeout(()=>el.remove(),3200)}
  async function api(path, options={}){const r=await fetch(`${API}${path}`,{credentials:"same-origin",headers:{"content-type":"application/json",...(options.headers||{})},...options});let data={};try{data=await r.json()}catch{}if(r.status===401){showOnly("#loginView");throw new Error("로그인이 필요합니다.")}if(!r.ok){const e=new Error(data.error||`HTTP ${r.status}`);e.data=data;e.status=r.status;throw e}return data}
  async function checkStatus(){try{const r=await fetch(`${API}/auth/status`,{cache:"no-store",credentials:"same-origin"});if(!r.ok)throw new Error();const s=await r.json();if(!s.configured){showOnly("#setupView");return}if(!s.authenticated){showOnly("#loginView");return}showOnly("#appView");await bootApp()}catch{showOnly("#setupView")}}
  async function login(ev){ev.preventDefault();const password=$("#passwordInput").value;$("#loginButton").disabled=true;$("#loginMessage").textContent="";try{await api("/auth/login",{method:"POST",body:JSON.stringify({password})});$("#passwordInput").value="";showOnly("#appView");await bootApp()}catch(e){$("#loginMessage").textContent=e.status===401?"비밀번호가 맞지 않습니다.":"로그인할 수 없습니다. Cloudflare 설정을 확인해주세요."}finally{$("#loginButton").disabled=false}}
  async function logout(){try{await api("/auth/logout",{method:"POST",body:"{}"})}catch{}showOnly("#loginView")}
  function nav(page){state.page=page;$$('.nav-item[data-page]').forEach(b=>b.classList.toggle("active",b.dataset.page===page));$$('.page').forEach(p=>p.classList.toggle("active",p.id===`page-${page}`));const [e,t]=titleMap[page];$("#pageEyebrow").textContent=e;$("#pageTitle").textContent=t;if(page==="records")loadRecords();if(page==="songs")loadSongs()}
  async function bootApp(){await loadMeta();await Promise.all([loadDashboard(),loadRecords(),loadSongs()]);}
  async function loadMeta(){try{const d=await api("/meta");state.meta=d;for(const id of ["dashboardYear","recordYear"]){const el=$("#"+id);const cur=el.value;el.innerHTML='<option value="">전체</option>'+d.years.map(y=>`<option value="${y}">${y}</option>`).join("");el.value=cur}const dis=$("#recordDistributor");const cur=dis.value;dis.innerHTML='<option value="">전체</option>'+d.distributors.map(x=>`<option>${esc(x)}</option>`).join("");dis.value=cur}catch(e){toast(e.message,"error")}}
  async function loadDashboard(){const year=$("#dashboardYear").value;try{const d=await api(`/dashboard${year?`?year=${encodeURIComponent(year)}`:""}`);const t=d.totals||{};$("#kpiSettlement").textContent=money(t.settlement_total);$("#kpiSettlementSub").textContent=year?`${year}년 합계`:"전체 기간";$("#kpiGross").textContent=money(t.gross_total);$("#kpiCount").textContent=num((Number(t.actual_total)||0)+(Number(t.estimated_total)||0));$("#kpiCountSub").textContent=`실제 ${num(t.actual_total)} · 추정 ${num(t.estimated_total)}`;$("#kpiSongs").textContent=`${num(t.songs_count)}곡`;$("#kpiRowsSub").textContent=`정산 ${num(t.rows_count)}건`;$("#kpiPending").textContent=money(t.pending_total);$("#kpiPendingSub").textContent=`${num(t.pending_rows)}건`;$("#dashboardUpdated").textContent=`${new Date(d.generatedAt).toLocaleString("ko-KR")} 기준`;renderMonthly(d.monthly||[]);renderRank("#topSongs",d.topSongs||[],x=>x.song_title,x=>x.project_artist,x=>money(x.amount));renderRank("#distributorList",d.distributors||[],x=>x.distributor,x=>`${num(x.rows_count)}건`,x=>money(x.amount))}catch(e){toast(e.message,"error")}}
  function renderMonthly(rows){const host=$("#monthlyChart");if(!rows.length){host.className="monthly-chart empty-state";host.textContent="데이터가 없습니다.";return}host.className="monthly-chart";const max=Math.max(...rows.map(x=>Number(x.amount)||0),1);host.innerHTML=rows.map(x=>{const h=Math.max(2,Math.round((Number(x.amount)||0)/max*100));return `<div class="month-col"><div class="month-bar-wrap"><div class="month-bar" style="height:${h}%" data-value="${money(x.amount)}"></div></div><div class="month-label">${esc(String(x.ym||"").slice(2))}</div></div>`}).join("");$("#monthlyRange").textContent=rows.length?`${rows[0].ym} ~ ${rows.at(-1).ym}`:"최근 12개월"}
  function renderRank(sel,rows,getName,getSub,getValue){const h=$(sel);if(!rows.length){h.className="rank-list empty-state";h.textContent="데이터가 없습니다.";return}h.className="rank-list";h.innerHTML=rows.map((x,i)=>`<div class="rank-item"><span class="rank-no">${i+1}</span><div class="rank-main"><b title="${esc(getName(x))}">${esc(getName(x))}</b><span>${esc(getSub(x)||"")}</span></div><div class="rank-value"><strong>${esc(getValue(x))}</strong></div></div>`).join("")}
  function recordQuery(limit=50){const p=new URLSearchParams({page:String(state.recordPage),limit:String(limit)});const map={q:"#recordSearch",year:"#recordYear",distributor:"#recordDistributor",payment:"#recordPayment"};for(const [k,s] of Object.entries(map)){const v=$(s).value.trim();if(v)p.set(k,v)}return p.toString()}
  async function loadRecords(){if($("#appView").classList.contains("hidden"))return;try{const d=await api(`/records?${recordQuery()}`);const body=$("#recordsBody");body.innerHTML=(d.rows||[]).map(r=>`<tr><td>${esc(r.settlement_ym||"-")}</td><td>${esc(r.distributor||"-")}</td><td>${esc(r.project_artist||"-")}</td><td class="song-cell" title="${esc(r.song_title)}">${esc(r.song_title)}</td><td>${esc(r.platform_source||"-")}</td><td class="num">${money(r.gross_revenue)}</td><td class="num">${money(r.settlement_amount)}</td><td class="num">${num(r.actual_count||r.estimated_count||0)}</td><td>${countBadge(r.count_type)}</td><td>${paymentBadge(r.payment_status)}</td><td><button class="row-action" data-delete-id="${r.id}" title="삭제">×</button></td></tr>`).join("")||'<tr><td colspan="11" class="empty-state">정산내역이 없습니다.</td></tr>';state.recordPages=Math.max(1,Math.ceil(Number(d.total||0)/Number(d.limit||50)));$("#pageInfo").textContent=`${state.recordPage} / ${state.recordPages}`;$("#prevPage").disabled=state.recordPage<=1;$("#nextPage").disabled=state.recordPage>=state.recordPages}catch(e){toast(e.message,"error")}}
  function countBadge(t){return t==="actual"?'<span class="badge actual">실제</span>':t==="estimated"?'<span class="badge estimated">추정</span>':'<span class="badge unknown">미제공</span>'}
  function paymentBadge(t){if(t==="지급")return '<span class="badge paid">지급</span>';if(t)return `<span class="badge pending">${esc(t)}</span>`;return '<span class="badge unknown">-</span>'}
  async function deleteRecord(id){if(!confirm("이 정산내역을 삭제할까요?"))return;try{await api(`/records?id=${id}`,{method:"DELETE"});toast("삭제했습니다.");await Promise.all([loadRecords(),loadDashboard(),loadSongs(),loadMeta()])}catch(e){toast(e.message,"error")}}
  async function loadSongs(){if($("#appView").classList.contains("hidden"))return;const q=$("#songSearch").value.trim();try{const d=await api(`/songs${q?`?q=${encodeURIComponent(q)}`:""}`);$("#songsBody").innerHTML=(d.rows||[]).map((r,i)=>`<tr><td>${i+1}</td><td class="song-cell"><b>${esc(r.song_title)}</b></td><td>${esc(r.project_artist||"-")}</td><td class="num">${money(r.gross_total)}</td><td class="num">${money(r.settlement_total)}</td><td class="num">${num(r.actual_total)}</td><td class="num">${num(r.estimated_total)}</td><td>${esc(r.latest_ym||"-")}</td></tr>`).join("")||'<tr><td colspan="8" class="empty-state">등록된 음원이 없습니다.</td></tr>'}catch(e){toast(e.message,"error")}}
  async function saveManual(ev){ev.preventDefault();const fd=new FormData($("#manualForm"));const obj=Object.fromEntries(fd.entries());for(const k of ["gross_revenue","settlement_amount","actual_count","estimated_count"])obj[k]=obj[k]===""?null:Number(obj[k]);obj.source_type="직접입력";try{await api("/records",{method:"POST",body:JSON.stringify(obj)});$("#manualDialog").close();$("#manualForm").reset();toast("정산내역을 저장했습니다.");await Promise.all([loadRecords(),loadDashboard(),loadSongs(),loadMeta()])}catch(e){toast(e.status===409?"이미 등록된 동일 정산내역입니다.":e.message,"error")}}
  async function exportCsv(){try{const d=await api(`/records?${recordQuery(500)}`);const cols=["settlement_ym","distributor","project_artist","song_title","platform_source","gross_revenue","settlement_amount","actual_count","estimated_count","count_type","payment_status","notes"];const csv=[cols.join(","),...d.rows.map(r=>cols.map(c=>`"${String(r[c]??"").replace(/"/g,'""')}"`).join(","))].join("\r\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}));a.download=`kenneth-settlement-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)}catch(e){toast(e.message,"error")}}
  function normalizeHeader(v){return String(v??"").replace(/\s+/g,"").replace(/[()（）]/g,"").toLowerCase()}
  const aliases={distributor:["유통사","distributor"],project_artist:["프로젝트/아티스트","프로젝트아티스트","아티스트","artist"],song_title:["곡명","음원명","track","title"],settlement_year:["정산년","연","year"],settlement_month:["정산월","월","month"],settlement_ym:["정산년월","년월","ym"],platform_source:["플랫폼/발생처","플랫폼","발생처","platform"],gross_revenue:["매출액","매출","grossrevenue"],settlement_amount:["정산액","settlementamount"],total_income:["총수익","수익","totalincome"],actual_count:["카운트","실제카운트","count"],adjusted_count:["보정카운트","추정카운트","adjustedcount"],zero_count_adjustment_count:["0카운트보정건수","제로카운트보정건수"],payment_status:["지급여부","지급상태","paymentstatus"],source_type:["원천구분","소스구분","sourcetype"],notes:["비고","메모","notes"]};
  const aliasLookup={};for(const [k,vals] of Object.entries(aliases))for(const v of vals)aliasLookup[normalizeHeader(v)]=k;
  function toNumber(v){if(v===null||v===undefined||v==="")return null;if(typeof v==="number"&&Number.isFinite(v))return v;const n=Number(String(v).replace(/[,₩원\s]/g,""));return Number.isFinite(n)?n:null}
  function parseYm(v,year,month){if(v instanceof Date&&!isNaN(v))return `${v.getFullYear()}-${String(v.getMonth()+1).padStart(2,"0")}`;if(typeof v==="number"&&window.XLSX){const d=XLSX.SSF.parse_date_code(v);if(d)return `${d.y}-${String(d.m).padStart(2,"0")}`};const s=String(v??"").trim();const m=s.match(/(20\d{2}|19\d{2})[^0-9]?([01]?\d)/);if(m)return `${m[1]}-${String(Number(m[2])).padStart(2,"0")}`;if(year&&month)return `${String(Number(year)).padStart(4,"0")}-${String(Number(month)).padStart(2,"0")}`;return null}
  function findHeaderRow(matrix){let best={idx:-1,score:0};for(let i=0;i<Math.min(matrix.length,30);i++){let score=0;for(const cell of matrix[i]||[])if(aliasLookup[normalizeHeader(cell)])score++;if(score>best.score)best={idx:i,score}}return best.score>=3?best.idx:-1}
  function median(a){const x=a.filter(v=>Number.isFinite(v)&&v>0).sort((a,b)=>a-b);if(!x.length)return null;const m=Math.floor(x.length/2);return x.length%2?x[m]:(x[m-1]+x[m])/2}
  function moneyBasis(r){return toNumber(r.total_income)??toNumber(r.settlement_amount)??toNumber(r.gross_revenue)}
  function estimateCounts(rows){const rates=new Map();const push=(k,rate)=>{if(!rate||!Number.isFinite(rate)||rate<=0)return;if(!rates.has(k))rates.set(k,[]);rates.get(k).push(rate)};for(const r of rows){const c=toNumber(r.actual_count),m=moneyBasis(r);if(c>0&&m>0){const rate=m/c;push(`sdp|${r.song_title}|${r.distributor}|${r.platform_source}`,rate);push(`sd|${r.song_title}|${r.distributor}`,rate);push(`dp|${r.distributor}|${r.platform_source}`,rate);push(`d|${r.distributor}`,rate);push("global",rate)}}let estimated=0,unknown=0;for(const r of rows){const actual=toNumber(r.actual_count);const adjusted=toNumber(r.adjusted_count);r.actual_count=actual>0?Math.round(actual):null;r.estimated_count=null;r.estimate_method="";r.estimate_confidence="";if(r.actual_count){r.count_type="actual";continue}if(adjusted>0){r.estimated_count=Math.round(adjusted);r.count_type="estimated";r.estimate_method="엑셀 보정카운트";r.estimate_confidence="high";estimated++;continue}const m=moneyBasis(r);if(!(m>0)){r.count_type="unknown";unknown++;continue}const candidates=[[`sdp|${r.song_title}|${r.distributor}|${r.platform_source}`,"동일 음원·유통사·플랫폼","high"],[`sd|${r.song_title}|${r.distributor}`,"동일 음원·유통사","medium"],[`dp|${r.distributor}|${r.platform_source}`,"동일 유통사·플랫폼","medium"],[`d|${r.distributor}`,"동일 유통사","low"],["global","전체 데이터","low"]];let done=false;for(const [k,label,conf] of candidates){const rate=median(rates.get(k)||[]);if(rate>0){r.estimated_count=Math.max(1,Math.round(m/rate));r.count_type="estimated";r.estimate_method=`${label} 1카운트당 수익 중앙값`;r.estimate_confidence=conf;estimated++;done=true;break}}if(!done){r.count_type="unknown";unknown++}}return{estimated,unknown}}
  async function parseFile(file){if(!window.XLSX)throw new Error("엑셀 파서가 로드되지 않았습니다. 인터넷 연결을 확인해주세요.");const buf=await file.arrayBuffer();const wb=XLSX.read(buf,{type:"array",cellDates:true});let parsed=[];let chosen="";for(const name of wb.SheetNames){const matrix=XLSX.utils.sheet_to_json(wb.Sheets[name],{header:1,defval:null,raw:true});const hi=findHeaderRow(matrix);if(hi<0)continue;const headers=(matrix[hi]||[]).map(h=>aliasLookup[normalizeHeader(h)]||null);const rows=[];for(let i=hi+1;i<matrix.length;i++){const line=matrix[i]||[];const r={};headers.forEach((key,j)=>{if(key)r[key]=line[j]});if(!r.song_title||String(r.song_title).trim()==="")continue;r.song_title=String(r.song_title).trim();r.distributor=String(r.distributor||"미분류").trim();r.project_artist=String(r.project_artist||"").trim();r.platform_source=String(r.platform_source||"").trim();r.settlement_ym=parseYm(r.settlement_ym,r.settlement_year,r.settlement_month);if(r.settlement_ym){r.settlement_year=Number(r.settlement_ym.slice(0,4));r.settlement_month=Number(r.settlement_ym.slice(5,7))}for(const k of ["gross_revenue","settlement_amount","total_income","actual_count","adjusted_count","zero_count_adjustment_count"])r[k]=toNumber(r[k]);r.payment_status=String(r.payment_status||"").trim();r.source_type=String(r.source_type||"엑셀업로드").trim();r.notes=String(r.notes||"").trim();rows.push(r)}if(rows.length>parsed.length){parsed=rows;chosen=name}}
    if(!parsed.length)throw new Error("지원되는 정산내역 헤더를 찾지 못했습니다.");const est=estimateCounts(parsed);return{rows:parsed,sheet:chosen,...est}}
  async function handleFile(file){if(!file)return;$("#fileInfo").classList.remove("hidden");$("#fileInfo").textContent=`${file.name} · ${(file.size/1024).toFixed(1)} KB · 분석 중…`;$("#importButton").disabled=true;try{const result=await parseFile(file);state.importRows=result.rows;$("#fileInfo").textContent=`${file.name} · 시트: ${result.sheet}`;renderImportPreview(result)}catch(e){state.importRows=[];$("#fileInfo").textContent=e.message;$("#importSummary").className="import-summary empty-state";$("#importSummary").textContent="파일을 분석하지 못했습니다.";$("#previewTableWrap").classList.add("hidden");toast(e.message,"error")}}
  function renderImportPreview(result){const rows=result.rows;const actual=rows.filter(r=>r.count_type==="actual").length;const est=rows.filter(r=>r.count_type==="estimated").length;const totalSettlement=rows.reduce((s,r)=>s+(Number(r.settlement_amount)||0),0);$("#previewCount").textContent=`${num(rows.length)}건`;$("#importSummary").className="import-summary";$("#importSummary").innerHTML=`<div class="summary-grid"><div class="summary-box"><span>인식 데이터</span><strong>${num(rows.length)}건</strong></div><div class="summary-box"><span>정산액 합계</span><strong>${money(totalSettlement)}</strong></div><div class="summary-box"><span>추정 카운트 행</span><strong>${num(est)}건</strong></div></div><p class="muted">실제 카운트 ${num(actual)}건 · 추정 ${num(est)}건 · 미제공 ${num(result.unknown)}건</p>`;$("#previewBody").innerHTML=rows.slice(0,12).map(r=>`<tr><td>${esc(r.settlement_ym||"-")}</td><td>${esc(r.distributor)}</td><td class="song-cell">${esc(r.song_title)}</td><td class="num">${money(r.settlement_amount)}</td><td class="num">${num(r.actual_count||r.estimated_count||0)}</td><td>${countBadge(r.count_type)}</td></tr>`).join("");$("#previewTableWrap").classList.remove("hidden");$("#importButton").disabled=false}
  async function importRows(){if(!state.importRows.length)return;$("#importButton").disabled=true;$("#importButton").textContent="저장 중…";try{const batchId=`xlsx-${Date.now()}`;const d=await api("/import",{method:"POST",body:JSON.stringify({batchId,rows:state.importRows})});toast(`${num(d.inserted)}건 저장 · 중복 ${num(d.duplicates)}건 제외`);state.importRows=[];$("#fileInput").value="";$("#fileInfo").classList.add("hidden");$("#previewTableWrap").classList.add("hidden");$("#previewCount").textContent="0건";$("#importSummary").className="import-summary empty-state";$("#importSummary").textContent="업로드가 완료되었습니다.";await Promise.all([loadMeta(),loadDashboard(),loadRecords(),loadSongs()])}catch(e){toast(e.message,"error")}finally{$("#importButton").disabled=!state.importRows.length;$("#importButton").textContent="D1에 저장"}}
  function bind(){
    $("#loginForm").addEventListener("submit",login);$("#logoutButton").addEventListener("click",logout);$("#retryStatusButton").addEventListener("click",checkStatus);$$('.nav-item[data-page]').forEach(b=>b.addEventListener("click",()=>nav(b.dataset.page)));$("#openImportButton").addEventListener("click",()=>nav("import"));$("#refreshButton").addEventListener("click",()=>Promise.all([loadMeta(),loadDashboard(),loadRecords(),loadSongs()]));$("#dashboardYear").addEventListener("change",loadDashboard);const reload=debounce(()=>{state.recordPage=1;loadRecords()});for(const id of ["recordSearch","recordYear","recordDistributor","recordPayment"])$("#"+id).addEventListener(id==="recordSearch"?"input":"change",reload);$("#prevPage").addEventListener("click",()=>{if(state.recordPage>1){state.recordPage--;loadRecords()}});$("#nextPage").addEventListener("click",()=>{if(state.recordPage<state.recordPages){state.recordPage++;loadRecords()}});$("#recordsBody").addEventListener("click",e=>{const b=e.target.closest("[data-delete-id]");if(b)deleteRecord(Number(b.dataset.deleteId))});$("#songSearch").addEventListener("input",debounce(loadSongs));$("#openManualButton").addEventListener("click",()=>$("#manualDialog").showModal());$("#manualForm").addEventListener("submit",saveManual);$("#exportCsvButton").addEventListener("click",exportCsv);$("#fileInput").addEventListener("change",e=>handleFile(e.target.files?.[0]));const dz=$("#dropZone");for(const ev of ["dragenter","dragover"])dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.add("drag")});for(const ev of ["dragleave","drop"])dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.remove("drag")});dz.addEventListener("drop",e=>handleFile(e.dataTransfer.files?.[0]));$("#importButton").addEventListener("click",importRows);
  }
  document.addEventListener("DOMContentLoaded",()=>{bind();checkStatus()});
})();
